# These file filter patterns are used by the action https://github.com/dorny/paths-filter
e2e-all:
  - '**/*'

e2e-docs:
  - '**/*.md'
  - '.github/workflows/e2e.deploy.docs.yml'
  - '.vuepress/*'
  - 'package.json'
